const bodyParser =require('body-parser') 
let data=[
    {
      id:0,
      title:'星期一',
      checkAll:false,
      list:[
        {
          id:10,
          name:'1',
          flag:false
        },
        {
          id:11,
          name:'2',
          flag:false
        },
        {
          id:12,
          name:'3',
          flag:false
        },
        {
          id:13,
          name:'4',
          flag:false
        },
        {
          id:14,
          name:'5',
          flag:false
        },
      ]
    },
    {
      id:1,
      title:'星期二',
      checkAll:false,
      list:[
        {
          id:15,
          name:'1',
          flag:false
        },
        {
          id:16,
          name:'2',
          flag:false
        },
        {
          id:17,
          name:'3',
          flag:false
        },
        {
          id:18,
          name:'4',
          flag:false
        },
        {
          id:19,
          name:'5',
          flag:false
        },
      ]
    },
  ]

module.exports = {
    lintOnSave:false,
    
    devServer:{
        before(app){
            app.use(bodyParser.json())

            app.get('/api/list',(req,res)=>{
                res.send({
                    code:200,
                    data,
                    message:'数据'
                })
            })
            app.post('/api/data',(req,res)=>{
                let {updata}=req.body
                data=updata
                res.send({
                    code:200,
                    data:updata,
                    message:'数据'
                })
            })
        }
    }
}